name: 'Publish release candidates to npm'

on:
  pull_request:
    # branches:
    #   - main
    paths-ignore:
      - '**/package.json'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Bump version
        run: pnpm bump:rc

      - name: Publish
        run: pnpm publish:rc

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Publish release candidate
          # branch: feature-123
          # commit_options: '--no-verify --signoff'
          # file_pattern: '*.php src/*.js tests/*.js'
